# Site
title:              Stéphane Manet
bio:                'Responsable projet de formation'
description:        "Responsable projet de formation spécialiste AFEST & blended learning."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/stephane-manet.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             fr_FR
url:                https://stephma.net
# https://stephma.net
# Jekyll
permalink:          /:title/
markdown:           kramdown
# highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-34832726-4
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            stephanemanet
facebook:           stephane.manet.cm
github-url:         stephmnt
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           stephanemanet
#xing:              username
instagram:          stephanemanet
#lastfm:            username
#tumblr:            username
medium:            '@stephanemanet'
#pinterest:         username
#foursquare:        username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
#  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
#  - feedjira

# collections:
#  - external_feed

#jekyll-mentions:
#    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

# Feedjira
feedurl: "http://feedjira.com/blog/feed.xml"
collections:
  - external_feed
